-- =============================================================================
-- V20260308000000__Initial_Schema.sql
-- Hissus Platform: PostGIS activation + core authentication schema
-- =============================================================================

-- 1. Enable PostGIS spatial extension
CREATE EXTENSION IF NOT EXISTS postgis;

-- =============================================================================
-- sys_ prefix: Authentication, Accounts, Roles, Permissions
-- =============================================================================

-- 2. sys_accounts (user accounts)
CREATE TABLE sys_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)  NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    is_deleted    BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255)
);

-- 3. sys_roles (role containers for permissions)
CREATE TABLE sys_roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- 4. sys_permissions (granular permission keys)
CREATE TABLE sys_permissions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key VARCHAR(255) NOT NULL UNIQUE
);

-- 5. sys_roles_permissions (role ↔ permission junction)
CREATE TABLE sys_roles_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT      NOT NULL REFERENCES sys_roles(id),
    permission_id BIGINT      NOT NULL REFERENCES sys_permissions(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (role_id, permission_id)
);

-- 6. sys_accounts_roles (account ↔ role junction)
CREATE TABLE sys_accounts_roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT      NOT NULL REFERENCES sys_accounts(id),
    role_id    BIGINT      NOT NULL REFERENCES sys_roles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (account_id, role_id)
);

-- =============================================================================
-- Indexes
-- =============================================================================

CREATE INDEX idx_sys_accounts_email ON sys_accounts (email) WHERE is_deleted = FALSE;
CREATE INDEX idx_sys_accounts_roles_account ON sys_accounts_roles (account_id);
CREATE INDEX idx_sys_roles_permissions_role ON sys_roles_permissions (role_id);

-- =============================================================================
-- Seed: Default roles and permissions
-- =============================================================================

INSERT INTO sys_roles (name) VALUES ('ADMIN'), ('STAFF'), ('CUSTOMER');

INSERT INTO sys_permissions (permission_key) VALUES
    ('QUOTATION_VIEW'),
    ('QUOTATION_CREATE'),
    ('QUOTATION_EDIT'),
    ('FINANCIAL_VIEW'),
    ('FINANCIAL_EDIT'),
    ('PRODUCT_VIEW'),
    ('PRODUCT_MANAGE'),
    ('USER_MANAGE'),
    ('JOB_VIEW'),
    ('JOB_MANAGE');
